import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type Props = Readonly<{
	children: React.ReactNode;
}>;
export default function RootLayout({ children }: Props) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<header className="h-[3em] bg-slate-200 flex flex-row gap-4 items-center px-5">
          <Link href="/">Home</Link>
          <Link href="/pagina1">Pagina 1</Link>
				</header>
				{children}
			</body>
		</html>
	);
}
